@extends('layouts.app')



























































































@endsection</div>    </form>        </div>            <button type="submit" class="btn btn-primary">{{ __('app.update') }}</button>            <a href="{{ route('restock.index') }}" class="btn btn-secondary">{{ __('app.cancel') }}</a>        <div class="d-flex justify-content-between mt-4">        </div>            @enderror                <div class="invalid-feedback">{{ $message }}</div>            @error('note')            <textarea class="form-control @error('note') is-invalid @enderror" id="note" name="note" rows="3">{{ old('note', $restock->note) }}</textarea>            <label for="note" class="form-label">{{ __('restock.note') }}</label>        <div class="mb-3">        </div>            </div>                @enderror                    <div class="invalid-feedback">{{ $message }}</div>                @error('restock_date')                       id="restock_date" name="restock_date" value="{{ old('restock_date', $restock->restock_date->format('Y-m-d')) }}" required>                <input type="date" class="form-control @error('restock_date') is-invalid @enderror"                 <label for="restock_date" class="form-label">{{ __('restock.restock_date') }} <span class="text-danger">*</span></label>            <div class="col-md-4 mb-3">            </div>                @enderror                    <div class="invalid-feedback">{{ $message }}</div>                @error('purchase_price_per_unit')                       value="{{ old('purchase_price_per_unit', $restock->purchase_price_per_unit) }}" step="0.01" min="0.01" required>                       id="purchase_price_per_unit" name="purchase_price_per_unit"                 <input type="number" class="form-control @error('purchase_price_per_unit') is-invalid @enderror"                 <label for="purchase_price_per_unit" class="form-label">{{ __('restock.purchase_price') }} <span class="text-danger">*</span></label>            <div class="col-md-4 mb-3">            </div>                @enderror                    <div class="invalid-feedback">{{ $message }}</div>                @error('quantity')                       id="quantity" name="quantity" value="{{ old('quantity', $restock->quantity) }}" min="1" required>                <input type="number" class="form-control @error('quantity') is-invalid @enderror"                 <label for="quantity" class="form-label">{{ __('restock.quantity') }} <span class="text-danger">*</span></label>            <div class="col-md-4 mb-3">        <div class="row">        </div>            </div>                @enderror                    <div class="invalid-feedback">{{ $message }}</div>                @error('product_id')                </select>                    @endforeach                        </option>                            {{ $product->name }}                        <option value="{{ $product->id }}" {{ old('product_id', $restock->product_id) == $product->id ? 'selected' : '' }}>                    @foreach($products->where('shop_id', old('shop_id', $restock->shop_id)) as $product)                <select class="form-select @error('product_id') is-invalid @enderror" id="product_id" name="product_id" required>                <label for="product_id" class="form-label">{{ __('restock.product') }} <span class="text-danger">*</span></label>            <div class="col-md-6 mb-3">            </div>                @enderror                    <div class="invalid-feedback">{{ $message }}</div>                @error('shop_id')                </select>                    @endforeach                        </option>                            {{ $shop->name }}                        <option value="{{ $shop->id }}" {{ old('shop_id', $restock->shop_id) == $shop->id ? 'selected' : '' }}>                    @foreach($shops as $shop)                    <option value="">{{ __('restock.select_shop') }}</option>                <select class="form-select @error('shop_id') is-invalid @enderror" id="shop_id" name="shop_id" required>                <label for="shop_id" class="form-label">{{ __('restock.shop') }} <span class="text-danger">*</span></label>            <div class="col-md-6 mb-3">        <div class="row">        @method('PUT')        @csrf    <form action="{{ route('restock.update', $restock->id) }}" method="POST"><div class="content-card"></div>    <p class="page-subtitle">{{ __('restock.edit_subtitle') }}</p>    <h1 class="page-title">{{ __('restock.edit_title') }}</h1><div class="mb-4">
@section('content')@section('title', __('restock.edit_title'))
