@extends('layouts.app')


































































































































@endsection@endpush</script>})();  });    });      branchSel.appendChild(o);      o.value = b.id; o.textContent = b.name;      var o = document.createElement('option');    branches.forEach(function (b) {    branchSel.innerHTML = '<option value="">All Branches</option>';    var branches = opt.dataset.branches ? JSON.parse(opt.dataset.branches) : [];    var opt      = shopSel.options[shopSel.selectedIndex];  shopSel.addEventListener('change', function () {  if (!shopSel) return;  var branchSel = document.getElementById('filter-branch-id');  var shopSel   = document.getElementById('filter-shop-id');(function () {<script>@push('scripts')</div>  </div></div>    @endif    <div class="p-3">{{ $subscriptions->links() }}</div>    </table></div>      </tbody>        @endforeach        </tr>          </td>            @endif              <span class="badge bg-secondary">—</span>            @else              <span class="badge bg-{{ $badgeClass }}">{{ (int) $daysLeft }}d</span>            @if($daysLeft !== null)          <td>          <td class="small">{{ $sub->ends_at?->format('d M Y') ?? 'Lifetime' }}</td>          <td class="small text-muted">{{ $sub->starts_at?->format('d M Y') ?? '—' }}</td>          <td>{{ $sub->plan->name }}</td>          <td>{{ $sub->branch?->name ?? '—' }}</td>          <td>{{ $sub->shop?->name ?? '—' }}</td>          <td><span class="badge bg-secondary text-capitalize">{{ $sub->user->role }}</span></td>          </td>            <div class="text-muted small">{{ $sub->user->email }}</div>            <div class="fw-semibold">{{ $sub->user->name }}</div>          <td>          <td class="text-muted small">{{ $sub->id }}</td>        <tr>        @endphp          $badgeClass = $daysLeft === null ? 'secondary' : ($daysLeft <= 7 ? 'danger' : ($daysLeft <= 30 ? 'warning' : 'success'));          $daysLeft = $sub->ends_at ? now()->diffInDays($sub->ends_at, false) : null;        @php        @foreach($subscriptions as $sub)      <tbody>      </thead>        </tr>          <th>Days Left</th>          <th>Expires</th>          <th>Started</th>          <th>Plan</th>          <th>Branch</th>          <th>Shop</th>          <th>Role</th>          <th>User</th>          <th>#</th>        <tr>      <thead class="table-light">    <div class="table-responsive"><table class="table table-hover align-middle mb-0">    @else      <div class="text-center py-5 text-muted"><i class="bi bi-inbox fs-1 d-block mb-2"></i>No active subscriptions found.</div>    @if($subscriptions->isEmpty())  <div class="card border-0 shadow-sm"><div class="card-body p-0">  </ul>    <li class="nav-item"><a class="nav-link active" href="{{ route('admin.subscriptions.active') }}"><i class="bi bi-check2-circle me-1"></i>Active Subscriptions</a></li>    <li class="nav-item"><a class="nav-link" href="{{ route('admin.subscriptions.index', ['status'=>'rejected']) }}">Rejected</a></li>    <li class="nav-item"><a class="nav-link" href="{{ route('admin.subscriptions.index', ['status'=>'approved']) }}">Approved</a></li>    <li class="nav-item"><a class="nav-link" href="{{ route('admin.subscriptions.index', ['status'=>'pending']) }}">Pending @if($counts['pending']>0)<span class="badge bg-warning text-dark ms-1">{{ $counts['pending'] }}</span>@endif</a></li>  <ul class="nav nav-tabs mb-3">  </form>    </div>      </div>        <a href="{{ route('admin.subscriptions.active') }}" class="btn btn-sm btn-outline-secondary"><i class="bi bi-x-lg"></i></a>        <button type="submit" class="btn btn-sm btn-primary flex-fill"><i class="bi bi-funnel-fill"></i> Filter</button>      <div class="col-sm-2 d-flex gap-1">      </div>        </select>          @endforeach            <option value="{{ $branch->id }}" {{ $branchId == $branch->id ? 'selected' : '' }}>{{ $branch->name }}</option>          @foreach($branches as $branch)          <option value="">All Branches</option>        <select name="branch_id" id="filter-branch-id" class="form-select form-select-sm">        <label class="form-label small mb-1">Branch</label>      <div class="col-sm-3">      </div>        </select>          @endforeach            </option>              {{ $shop->name }}              {{ $shopId == $shop->id ? 'selected' : '' }}>              data-branches="{{ $shop->branches->map(fn($b) => ['id'=>$b->id,'name'=>$b->name])->toJson() }}"            <option value="{{ $shop->id }}"          @foreach($shops as $shop)          <option value="">All Shops</option>        <select name="shop_id" id="filter-shop-id" class="form-select form-select-sm">        <label class="form-label small mb-1">Shop</label>      <div class="col-sm-3">      </div>        <input type="text" name="search" class="form-control form-control-sm" placeholder="Name or email…" value="{{ $search }}">        <label class="form-label small mb-1">Search User</label>      <div class="col-sm-4">    <div class="row g-2 align-items-end">  <form method="GET" action="{{ route('admin.subscriptions.active') }}" class="card border-0 shadow-sm mb-3 p-3">  {{-- Filter Bar --}}  </div>    <div class="col-sm-4"><div class="card border-0 shadow-sm text-center p-3"><div class="fs-2 fw-bold text-danger">{{ $counts['rejected'] }}</div><div class="small text-muted">Rejected</div></div></div>    <div class="col-sm-4"><div class="card border-0 shadow-sm text-center p-3"><div class="fs-2 fw-bold text-success">{{ $counts['approved'] }}</div><div class="small text-muted">Approved</div></div></div>    <div class="col-sm-4"><div class="card border-0 shadow-sm text-center p-3"><div class="fs-2 fw-bold text-warning">{{ $counts['pending'] }}</div><div class="small text-muted">Pending Payments</div></div></div>  <div class="row g-3 mb-4">  </div>    <h4 class="fw-bold mb-0"><i class="bi bi-check2-circle me-2"></i>Active Subscriptions</h4>  <div class="d-flex align-items-center justify-content-between mb-4"><div class="container-fluid py-4">@section('content')@section('title', 'Active Subscriptions')
