<?php































































































































































}    }        ]);            'products' => $products,        return response()->json([            ->get();            })                $query->whereRaw('quantity <= minimum_stock');                }                    $query->where('branch_id', $branchId);                if ($branchId) {            ->whereHas('branchStocks', function ($query) use ($branchId) {        }])            }                $query->where('branch_id', $branchId);            if ($branchId) {        $products = Product::with(['category', 'branchStocks' => function ($query) use ($branchId) {        $branchId = $request->branch_id;    {    public function lowStock(Request $request): JsonResponse     */     * Get products with low stock alert    /**    }        ]);            'message' => 'Product deleted successfully',        return response()->json([        $product->delete();    {    public function destroy(Product $product): JsonResponse     */     * Remove the specified product    /**    }        ]);            'product' => $product->load('category'),            'message' => 'Product updated successfully',        return response()->json([        $product->update($validator->validated());        }            ], 422);                'errors' => $validator->errors()                'message' => 'Validation error',            return response()->json([        if ($validator->fails()) {        ]);            'is_active' => 'boolean',            'image' => 'nullable|string',            'minimum_stock' => 'nullable|numeric|min:0',            'selling_price' => 'sometimes|required|numeric|min:0',            'purchase_price' => 'sometimes|required|numeric|min:0',            'unit' => 'sometimes|required|string',            'description' => 'nullable|string',            'category_id' => 'sometimes|required|exists:categories,id',            'barcode' => 'nullable|string|unique:products,barcode,' . $product->id,            'sku' => 'sometimes|required|string|unique:products,sku,' . $product->id,            'name' => 'sometimes|required|string|max:255',        $validator = Validator::make($request->all(), [    {    public function update(Request $request, Product $product): JsonResponse     */     * Update the specified product    /**    }        ]);            'product' => $product->load(['category', 'branchStocks.branch']),        return response()->json([    {    public function show(Product $product): JsonResponse     */     * Display the specified product    /**    }        ], 201);            'product' => $product->load('category'),            'message' => 'Product created successfully',        return response()->json([        $product = Product::create($validator->validated());        }            ], 422);                'errors' => $validator->errors()                'message' => 'Validation error',            return response()->json([        if ($validator->fails()) {        ]);            'is_active' => 'boolean',            'image' => 'nullable|string',            'minimum_stock' => 'nullable|numeric|min:0',            'selling_price' => 'required|numeric|min:0',            'purchase_price' => 'required|numeric|min:0',            'unit' => 'required|string',            'description' => 'nullable|string',            'category_id' => 'required|exists:categories,id',            'barcode' => 'nullable|string|unique:products,barcode',            'sku' => 'required|string|unique:products,sku',            'name' => 'required|string|max:255',        $validator = Validator::make($request->all(), [    {    public function store(Request $request): JsonResponse     */     * Store a newly created product    /**    }        return response()->json($products);        $products = $query->latest()->paginate($request->per_page ?? 15);        }            $query->where('is_active', $request->is_active);        if ($request->has('is_active')) {        // Filter by active status        }            $query->where('category_id', $request->category_id);        if ($request->has('category_id')) {        // Filter by category        }            });                    ->orWhere('barcode', 'like', "%{$search}%");                    ->orWhere('sku', 'like', "%{$search}%")                $q->where('name', 'like', "%{$search}%")            $query->where(function ($q) use ($search) {            $search = $request->search;        if ($request->has('search')) {        // Search functionality        $query = Product::with(['category', 'branchStocks.branch']);    {    public function index(Request $request): JsonResponse     */     * Display a listing of products    /**{class ProductController extends Controlleruse Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;use Illuminate\Http\JsonResponse;use App\Models\Product;use App\Http\Controllers\Controller;namespace App\Http\Controllers\Api;